spring:
  security:
    oauth2:
      client:   
        registration:
          google:
            client-id: # Client obitido no Google OAuth
            client-secret: # Client Secret obtido no Google OAuth
